import { useRef, useMemo } from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { useReducedMotion } from '../hooks/useReducedMotion'

// Soft circular texture generated by code — no square pixel edges
function createSoftCircleTexture() {
  const size = 64
  const canvas = document.createElement('canvas')
  canvas.width = size
  canvas.height = size
  const ctx = canvas.getContext('2d')
  const gradient = ctx.createRadialGradient(size / 2, size / 2, 0, size / 2, size / 2, size / 2)
  gradient.addColorStop(0, 'rgba(255,255,255,0.9)')
  gradient.addColorStop(0.4, 'rgba(255,255,255,0.4)')
  gradient.addColorStop(1, 'rgba(255,255,255,0)')
  ctx.fillStyle = gradient
  ctx.fillRect(0, 0, size, size)
  return new THREE.CanvasTexture(canvas)
}

// Low-density particle field with gentle autonomous drift
function ParticleField() {
  const ref = useRef()
  const COUNT = 180

  const { positions, colors } = useMemo(() => {
    const positions = new Float32Array(COUNT * 3)
    const colors = new Float32Array(COUNT * 3)
    // Muted organic palette matching design tokens
    const palette = [
      new THREE.Color('#3A82CA'), // pri blue
      new THREE.Color('#816AB7'), // sec violet
      new THREE.Color('#48B0A1'), // acc teal
      new THREE.Color('#9CC156'), // green
      new THREE.Color('#FBB027'), // warm gold
    ]
    for (let i = 0; i < COUNT; i++) {
      positions[i * 3]     = (Math.random() - 0.5) * 14
      positions[i * 3 + 1] = (Math.random() - 0.5) * 10
      positions[i * 3 + 2] = (Math.random() - 0.5) * 6
      const c = palette[Math.floor(Math.random() * palette.length)]
      colors[i * 3]     = c.r
      colors[i * 3 + 1] = c.g
      colors[i * 3 + 2] = c.b
    }
    return { positions, colors }
  }, [])

  const texture = useMemo(() => createSoftCircleTexture(), [])

  // Very slow, organic drift — no sudden accelerations
  useFrame((state) => {
    if (!ref.current) return
    const t = state.clock.elapsedTime
    ref.current.rotation.y = t * 0.018
    ref.current.rotation.x = Math.sin(t * 0.009) * 0.12
    ref.current.position.y = Math.sin(t * 0.07) * 0.15
  })

  return (
    <points ref={ref}>
      <bufferGeometry>
        <bufferAttribute
          attach="attributes-position"
          args={[positions, 3]}
        />
        <bufferAttribute
          attach="attributes-color"
          args={[colors, 3]}
        />
      </bufferGeometry>
      <pointsMaterial
        size={0.06}
        map={texture}
        vertexColors
        transparent
        opacity={0.55}
        sizeAttenuation
        depthWrite={false}
        blending={THREE.AdditiveBlending}
      />
    </points>
  )
}

export default function CanvasBg() {
  const prefersReduced = useReducedMotion()

  // Unmount canvas entirely when user prefers reduced motion
  if (prefersReduced) {
    return (
      <div
        className="fixed inset-0 -z-10"
        style={{
          background: 'radial-gradient(ellipse at 70% 10%, rgba(129,106,183,0.07) 0%, transparent 60%), radial-gradient(ellipse at 20% 80%, rgba(72,176,161,0.05) 0%, transparent 55%)',
        }}
        aria-hidden="true"
      />
    )
  }

  return (
    <div className="fixed inset-0 -z-10 pointer-events-none" aria-hidden="true">
      <Canvas
        camera={{ position: [0, 0, 7], fov: 55 }}
        gl={{ antialias: false, alpha: true, powerPreference: 'low-power' }}
        dpr={[1, 1.5]}
      >
        <ParticleField />
      </Canvas>
    </div>
  )
}
